version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: techpit_db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-db-data:/var/lib/mysql
    tty: true
    stdin_open: true
volumes:
  mysql-db-data:
    driver: local

